#### Do not touch the version thing if you dont know what you are doing ####
version: "0.1.0"
####


################## Join/Leave Message Configuration ####################
webhookURL: "Your Discord Webhook URL"
webhookUsername: "DiscordNotify"

player-join-message: "{Player} joined the Server :)"
player-leave-message: "{Player} left the Server :("


################## Chat Message Configuration ####################

chat-to-discord: true

chat-webhookURL: "Another Discord Webhook URL"